apiVersion: apps/v1
kind: Deployment
metadata:
  name: moura-app
  labels:
    app: moura
spec:
  replicas: 3
  selector:
    matchLabels:
      app: moura
  template:
    metadata:
      labels:
        app: moura
    spec:
      containers:
      - name: moura-app
        image: mouralol23/app-moura:latest
        ports:
        - containerPort: 80
